### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by anlutro** [anlutro/ircbot#2]
Currently, `100 nok in eur` will be matched by the conversion regex but nothing will be done because the DuckDuckGo API doesn't do currency conversion.

Maybe find some alternate API that can do what we need?

**Comment by andrewdodd13** [comment]
Use this: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

If you need to go from GBP to USD do it by going to EUR first. There's basically 0 arbitrage on FX these days.
