### ISSUE TITLE
systemctl restart taking a long time

### ISSUE THREAD

**Issue by anlutro** [anlutro/ircbot#7]
`systctl restart ircbot` takes a long time after adding the HTTP server.

Are we sending the right termination signal? Do we need to specify one in the .service file?

Are we responding properly to SIGQUIT/SIGTERM?

**Comment by x89** [comment]
`SIGKILL` or bust.

**Comment by anlutro** [comment]
Maybe fixed by https://github.com/anlutro/ircbot/commit/7ccac02546ea912ff42c0cd84acdce2bf6641890

**Comment by anlutro** [comment]
Yep, fixed

**Comment by anlutro** [comment]
Un-fixed in https://github.com/anlutro/ircbot/commit/51618d0e437bb0f6d1664e903f7b38bef61b5cad - needs more investigation.

**Comment by anlutro** [comment]
Fixed in https://github.com/anlutro/ircbot/commit/e9305363fbf6c4a5d79a3f9b24d01fe9dea8181f, properly this time
